channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=23.3.1
- pip:
  - mlflow==2.17.0
  - alpha-vantage==3.0.0
  - cloudpickle==3.1.0
  - matplotlib==3.8.2
  - mplfinance==0.12.10b0
  - numpy==1.26.2
  - openai==1.47.0
  - pandas==2.1.3
  - pygments==2.17.2
  - python-dotenv==1.0.1
name: mlflow-env
